### PR TITLE
Adding Norway, Fylker, municipalities

### PR DESCRIPTION
**Pull request by Amgine0**
Added Norway, 18 fylke, 422 municipalities

### CODE REVIEW

**Comment by fisharebest** [comment]
Thanks!

**Comment by fisharebest** [comment]
@Amgine0 

I guess you have a script to import from wikipedia?

Two things.

Firstly, in the `data.geojson` files, the place names have underscores in the names instead of spaces.  e.g. `"fr": "Comté_d'Østfold",` instead of `"fr": "Comté d'Østfold",`

Secondly, the filenames need to contain ASCII only.  Different filesytems have different representations, so we end up with things like:

```
$ git status
	...
	modified:   data/Norway/data.geojson
	modified:   "data/Norway/\303\230stfold/data.geojson"
```

Do you want to create another pull-request for this, or do you want me to do it?

**Comment by fisharebest** [comment]
The tools/repair command will now replace underscores with spaces.
I have used it to update the Norway data.

**Comment by Amgine0** [comment]
I have been using tools/wiki-place for importing from wikipedia. I could rig my own script to parse the data via the api, but I do not know the geojson format.

I should mention the translations pulled from en.WP will include a percentage with incorrect names based on mediawiki's title collision.

**Pull request merged**
